Task_1_2_1
NataliaResh/OOP pull request #10
Opened 2024-09-23 09:34 UTC by NataliaResh

2024-10-05 09:10 UTC, Sharapov-Maksim requested changes
Хорошая работа, мягкий дедлайн зачтён

2024-10-05 09:10 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/sys/pro/TopologicalSort.java
> +     */
Думаю тут можно ещё указать название использованного алгоритма, если оно есть

2024-10-05 09:10 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +public interface Graph {
Нужно будет добавить тестов, сейчас метод `removeEdge` совсем не тестируется, и остальные методы не все покрыты

2024-10-06 10:41 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +                }
fix

2024-10-06 10:45 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Utils.java
> +    }
fix

2024-10-06 10:57 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +        }
fix

2024-10-06 10:58 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +    int getNodesCapacity();
Добавила геттер для количества вершин, для capacity оставила, так как он используется в методе isEqual

2024-10-06 11:00 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/AdjacencyMatrixGraph.java
> +    static final int MAX_NODES_COUNT = 1024;
Изначально подумала, что стоит ограничить максимальный номер вершины, чтобы запретить создавать слишком большие массивы для графов. Убрала эту проверку

2024-10-06 11:00 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/AdjacencyMatrixGraph.java
> +        consistedNodes[node] = true;
fix

2024-10-06 11:00 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/TopologicalSort.java
> +     */
fix

2024-10-06 11:00 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +public interface Graph {
fix

2024-10-07 12:49 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +    int getNodesCapacity();
Я понимаю, что вам хочется обобщить `isEqual`, но `capacity` - это деталь реализации. Если хотите выносить её в публичное API, то вам нужно очень подробно описать метод в javadoc. По ходу этого описания вы, вероятно, перехотите выносить его в публичное API.

Сейчас же из слов `Returns max count of nodes.` не следует, что это число вобще-то растёт, и что, соответственно, оно не ограничивает вместимость графа. И все ограничения, которые вы тут напишите, все наследники должны будут соблюдать - негативный эффект на масштабируемость.

Вижу здесь 2 варианта:
1. Убрать реализацию `isEqual` из интерфейса и продублировать её во всех наследниках.
2. Сделать промежуточный абстрактный класс, в котором будет `protected` метод `getNodesCapacity` и нужная вам реализация `isEqual`

2024-10-07 14:01 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +    int getNodesCapacity();
А если добавить метод `getMaxNodeNumber` в` Graph`, который не будет зависеть от реализации и который уже вызывать в общих методах где был `getCapacity`?

2024-10-08 03:48 UTC, Sharapov-Maksim commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +    int getNodesCapacity();
Можно и так, да

2024-10-12 09:06 UTC, Sharapov-Maksim requested changes
Опишите, как добавить в имеющуюся объектную модель новый способ представления графа?

2024-10-12 10:26 UTC, NataliaResh commented
Для того, чтобы добавить в имеющуюся объектную модель новый способ представления графа, необходимо добавить класс, имплементирующий интерфейс `Graph` `class NameOfClass implements Graph` и который будет реализовывать все методы интерфейса `Graph`.

2024-10-12 10:27 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/Graph.java
> +    int getMaxNodeNumber();
fix

2024-10-12 10:27 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/AdjacencyMatrixGraph.java
> +    }
fix

2024-10-12 10:27 UTC, NataliaResh commented on Task_1_2_1/src/main/java/sys/pro/AdjacencyMatrixGraph.java
> +        }
fix

2024-10-12 10:27 UTC, NataliaResh commented on Task_1_2_1/src/test/java/sys/pro/AdjacencyMatrixGraphTest.java
> +    }
fix

2024-10-12 10:28 UTC, NataliaResh commented on Task_1_2_1/src/test/java/sys/pro/AdjacencyMatrixGraphTest.java
> +        }
fix

2024-10-13 03:37 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-10-13 16:15 UTC, merged