Task_1_2_2
NataliaResh/OOP pull request #11
Opened 2024-10-07 10:33 UTC by NataliaResh

2024-10-13 06:07 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён

2024-10-13 06:07 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +        if (obj == null || obj.getClass() != this.getClass()) {
Лучше написать `!(obj instanceof HashTable<?,?>)`, лучше читаться будет

Для справки:
`getClass()` возвращает класс без информации о дженеричных типах, поэтому и текущая и предложенная реализации посчитают равными пустые таблицы с разными типами элементов:
```
        HashTable<Integer, int[]> a = new HashTable<>();
        HashTable<Integer, Integer> b = new HashTable<>();
        Assert.assertTrue(a.equals(b));
        a.put(1, new int[1]);
        b.put(1, 1);
        Assert.assertFalse(a.equals(b));
```

2024-10-14 10:20 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +        size++;
Исправила, теперь значение обновляется (вызывается `updateValue`)

2024-10-14 10:22 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +     */
Исправила на то, что теперь можно использовать `null` как ключ, теперь это исключение не выбрасывается

2024-10-14 10:24 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +    public void put(K key, V value) {
Исправила, добавила тесты, где `key = null` и `value = null`

2024-10-14 10:25 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +    }
Исправила

2024-10-14 10:28 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +    private int expectedModCount = 0;
fix

2024-10-14 10:43 UTC, NataliaResh commented on Task_1_2_2/src/main/java/sys/pro/HashTable.java
> +        if (obj == null || obj.getClass() != this.getClass()) {
Исправила, теперь классы проверяю при сравнении значений

2024-10-15 04:15 UTC, merged

2024-10-15 04:22 UTC, Sharapov-Maksim commented
Задание зачтено на семинаре