Task_1_1_1
NataliaResh/OOP pull request #7
Opened 2024-09-08 04:29 UTC by NataliaResh

2024-09-08 06:17 UTC, Sharapov-Maksim requested changes
Хорошая работа, только одно замечание могу сделать

2024-09-08 06:17 UTC, Sharapov-Maksim commented on Task_1_1_1/make.sh
> +javac -d ./build/classes/java/main ./src/main/java/*.java
А давайте всё таки сделаем функцию `main` и добавим в скрипт запуск приложения через `java`

2024-09-08 11:55 UTC, NataliaResh commented on Task_1_1_1/make.sh
> +javac -d ./build/classes/java/main ./src/main/java/*.java
fixed

2024-09-09 00:32 UTC, Sharapov-Maksim approved these changes

2024-09-09 00:32 UTC, merged