Task_1_1_2
NataliaResh/OOP pull request #8
Opened 2024-09-10 12:29 UTC by NataliaResh

2024-09-10 14:14 UTC, Sharapov-Maksim commented
Я так понимаю представленное решение уже можно ревьюить полноценно? Или остались какие-то недоделки? 

В любом случае, мягкий дедлайн засчитан, ревью попозже будет

2024-09-10 14:19 UTC, NataliaResh commented
Да, решение можно ревьюить

2024-09-12 15:08 UTC, Sharapov-Maksim requested changes
Правки выдал

2024-09-12 15:08 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/PackTest.java
> +public class PackTest {
Можно сделать более сложные тесты. Например, что из колоды всегда достаются разные карты

2024-09-12 15:08 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Pack.java
> +    public Card getCard() {
А что произойдёт, если карты вдруг закончатся? =)

Я понимаю, что в этой игре такое невозможно. Но ведь судя по javadoc, вашу колоду ничто не мешает переиспользовать для какой-нибудь другой игры

2024-09-12 15:08 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Game.java
> +    private void playerMove() {
На такие `move` игроков можно будет и тесты сделать, как мне кажется

2024-09-13 15:54 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Player.java
> +    public static final int ACE_WEIGHT = 11;
fix

2024-09-13 15:55 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Player.java
> +        if (card.getWeight() == ACE_WEIGHT && cardScore + ACE_WEIGHT > 21) {
fix

2024-09-13 16:01 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Dealer.java
> +public class Dealer extends Player {
При наследовании дочерний класс получает поля и методы от родителя, при чем возможность использовать их в дочернем классе зависит от типа доступа. В Java есть 3 вида доступа, public и protected позволяют использовать поля и методы в новых методах дочернего класса, private не видны из дочернего класса. В данном случае удобно Dealer отнаследоваться от Player, так как у Dealer есть свои методы, необходимые для этого класса и не нужные для родительского, но он также является Player, так как все поля из Player необходимы Dealer. Это позволяет избежать дублирования кода, а также удобно реализовать функции вида foo(Player player), которые могут принимать не только объекты класса Player, но и объекты классов наследников.

2024-09-13 16:02 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Game.java
> +                exitWithLog("gg");
fix, sorry for unreadble logs)

2024-09-13 16:02 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Game.java
> +        winner.incScore();
fix

2024-09-13 16:05 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Game.java
> +    private void playerMove() {
Мне непонятно, что именно предполагается реализовать в методе `move` в класct `Player`, если ход - это выдача карт в цикле, обернутая выводами

2024-09-13 16:06 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Player.java
> +        if (card.getWeight() == ACE_WEIGHT && cardScore + ACE_WEIGHT > 21) {
fix

2024-09-13 16:09 UTC, NataliaResh commented on Task_1_1_2/src/test/java/blackjack/PackTest.java
> +public class PackTest {
fix

2024-09-13 16:09 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Pack.java
> +    public Card getCard() {
fix

2024-09-14 08:25 UTC, Sharapov-Maksim requested changes

2024-09-14 08:25 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Game.java
> +    private void playerMove() {
Логично, тут действительно нечего выносить в Player

2024-09-14 08:25 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/PackTest.java
> +public class PackTest {
Я имел ввиду, что последовательные вызовы `getCard()` будут возвращать разные карты. Вам для проверки `Pack#packCards` пришлось полю модификатор доступа изменить, это излишне

2024-09-14 08:25 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Pack.java
> +            exit("Pack is empty!");
А если бы мы тут, например, возвращали `null`, то пустую колоду можно было бы протестировать даже. В любом случае, в javadoc надо описать поведение при опустошении колоды

2024-09-14 08:25 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/GameIO.java
> +        System.out.println(error);
Можно даже `System.err.println` заиспользовать в таком случае

2024-09-14 09:15 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Card.java
> +    public static final int ACE_WEIGHT = 11;
fix

2024-09-14 09:16 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/Pack.java
> +            exit("Pack is empty!");
changed to `null`

2024-09-14 09:17 UTC, NataliaResh commented on Task_1_1_2/src/main/java/blackjack/GameIO.java
> +        System.out.println(error);
this function don't need now

2024-09-14 09:17 UTC, NataliaResh commented on Task_1_1_2/src/test/java/blackjack/PackTest.java
> +public class PackTest {
fix

2024-09-15 05:02 UTC, Sharapov-Maksim approved these changes
Все замечания исправлены

2024-09-15 05:02 UTC, merged