Task_1_1_3
NataliaResh/OOP pull request #9
Opened 2024-09-15 06:01 UTC by NataliaResh

2024-09-15 06:52 UTC, NataliaResh commented
Решение без доп. заданий

2024-09-24 04:01 UTC, NataliaResh commented
Добавила решение доп. заданий, жду ревью

2024-09-28 10:43 UTC, Sharapov-Maksim requested changes
Хорошая работа. Мягкий дедлайн зачтён. Замечания выдал

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/sys/pro/Variable.java
> +            throw new NotEnoughSignificationsExpression("Not all variables have value!");
В сообщение предлагаю добавить название переменной, которая не нашлась, для удобства. Или даже в сам объект исключения, если хотите

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/sys/pro/Utils.java
> +    public static void pass() {
Объясните смысл этого метода, пожалуйста. Здесь планируется доделать какую-то реализацию?

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/sys/pro/Variable.java
> +    protected String var;
final

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/sys/pro/Number.java
> +    protected int val;
final

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/sys/pro/ExpressionTest.java
> +public class ExpressionTest {
Давайте разобъём тесты по отдельным классам в соответствии с тестируемой операцией. А в этом классе оставим только более общие тесты на композиции операций

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/sys/pro/ExpressionTest.java
> +    public void simplifyMultiplicationTest() {
Если пользуетесь IDEA, можно запустить тесты с отслеживанием покрытия
![image](https://github.com/user-attachments/assets/8827f7a2-8fa4-49b2-aae7-9080bf1eb6c9)
и мы увидим такую картину:
![image](https://github.com/user-attachments/assets/fef70a57-0622-495c-a132-71989a72b4ce)
где красным помечены строчки, которые не запускались ни в одном тесте.

Делаем вывод: нужно добавить более сложные тесты, в которых будут переменные. Потому что сейчас только у `Sub` покрылась хорошо логика упрощения.

2024-09-28 10:43 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/sys/pro/ParserTest.java
> +public class ParserTest {
Надо бы добавить тестов на выражения без скобок, из доп. условия

2024-09-29 03:23 UTC, NataliaResh commented on Task_1_1_3/src/main/java/sys/pro/Binary.java
> +    protected Expression left;
fix

2024-09-29 03:26 UTC, NataliaResh commented on Task_1_1_3/src/main/java/sys/pro/Variable.java
> +            throw new NotEnoughSignificationsExpression("Not all variables have value!");
fix

2024-09-29 08:51 UTC, NataliaResh commented on Task_1_1_3/src/main/java/sys/pro/Utils.java
> +    public static void pass() {
Решила всё-таки избавиться от конструкции `try/catch` в методе `simplify`, это всё же излишне. Добавила метод `safeEval`, который вызывается после проверки, что в выражении нет переменных

2024-09-29 08:53 UTC, NataliaResh commented on Task_1_1_3/src/main/java/sys/pro/Variable.java
> +    protected String var;
fix

2024-09-29 08:54 UTC, NataliaResh commented on Task_1_1_3/src/main/java/sys/pro/Number.java
> +    protected int val;
fix

2024-09-29 09:57 UTC, NataliaResh commented on Task_1_1_3/src/test/java/sys/pro/ExpressionTest.java
> +public class ExpressionTest {
fix

2024-09-29 09:58 UTC, NataliaResh commented on Task_1_1_3/src/test/java/sys/pro/ParserTest.java
> +public class ParserTest {
fix

2024-09-30 06:32 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/sys/pro/Utils.java
> +    public static void pass() {
Хорошо получилось

2024-09-30 06:53 UTC, Sharapov-Maksim approved these changes
Задание выполнено. Доп. баллы: 2

PR можно мёржить

2024-09-30 06:53 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/sys/pro/ExpressionTest.java
>  public class ExpressionTest {
Раз уж класс опустел, можно и удалить

2024-09-30 10:02 UTC, NataliaResh commented on Task_1_1_3/src/test/java/sys/pro/ExpressionTest.java
>  public class ExpressionTest {
удалила

2024-09-30 10:03 UTC, merged